name: DevOps CI Lab

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x app.sh test.sh

      - name: Run tests
        run: ./test.sh
